Parameters:
  DatabaseImplementation:
    Default: 'Amazon Aurora PostgreSQL'
    Description: 'Database Engine to use. PostgreSQL or Amazon Aurora Clustered PostgreSQL'
    AllowedValues:
      - 'Amazon Aurora PostgreSQL'
      - 'PostgreSQL'
    ConstraintDescription: Must be 'true' or 'false'.
    Type: String
  DBSecurityGroup:
    Description: "ID of the security group (e.g. sg-0234se). One will be created for you if left empty."
    Type: String
    Default: ''
  DBAutoMinorVersionUpgrade: 
    AllowedValues: 
      - "true"
      - "false"
    Default: "false"
    Description: "Select true/false to setup Auto Minor Version upgrade. e.g. PostgreSQL 9.6.8 -> 9.6.11"
    Type: String
  DBBackupRetentionPeriod: 
    Default: "7"
    Description: "The number of days for which automatic database snapshots are retained."
    Type: String
  DBInstanceClass:
    AllowedValues:
      - db.m4.large
      - db.m4.xlarge
      - db.m4.2xlarge
      - db.m4.4xlarge
      - db.m4.10xlarge
      - db.m4.16xlarge
      - db.r4.large
      - db.r4.xlarge
      - db.r4.2xlarge
      - db.r4.4xlarge
      - db.r4.8xlarge
      - db.r4.16xlarge
      - db.t2.medium
      - db.t2.large
      - db.t2.xlarge
      - db.t2.2xlarge
    ConstraintDescription: Must be a valid RDS instance class from the list
    Description: RDS instance type (must be r4 family if using Amazon Aurora)
    Type: String
  DBIops:
    Default: 1000
    ConstraintDescription: Must be in the range 1000 - 30000.
    Description: 'Must be in the range of 1000 - 30000 and a multiple of 1000. This value is only used with Provisioned IOPS. Note: The ratio of IOPS per allocated-storage must be between 3.00 and 10.00. Not used for Amazon Aurora.'
    MinValue: 1000
    MaxValue: 30000
    Type: Number
  DBMasterUserPassword:
    AllowedPattern: '(?=^.{6,255}$)((?=.*\\d)(?=.*[A-Z])(?=.*[a-z])|(?=.*\\d)(?=.*[^A-Za-z0-9])(?=.*[a-z])|(?=.*[^A-Za-z0-9])(?=.*[A-Z])(?=.*[a-z])|(?=.*\\d)(?=.*[A-Z])(?=.*[^A-Za-z0-9]))^.*'
    ConstraintDescription: Must be at least 8 characters and include 1 uppercase, 1 lowercase, 1 number, 1 (non / @ \" ') symbol
    Description: Password for the master ('postgres') account. Must be at least 8 characters and include 1 uppercase, 1 lowercase, 1 number, 1 (non / @ \" ') symbol.
    MinLength: 8
    MaxLength: 128
    NoEcho: true
    Type: String
  DBMultiAZ:
    Description: When DBEngine is 'PostgreSQL', this will determine whether to provision a multi-AZ RDS instance. When DBEngine is 'Amazon Aurora PostgreSQL', this will determine whether to provision a single or a multi node Amazon Aurora cluster.
    Default: true
    AllowedValues:
      - true
      - false
    ConstraintDescription: Must be 'true' or 'false'.
    Type: String
  DBAllocatedStorage:
    Default: 10
    Description: Database allocated storage size, in gigabytes (GB). If you choose Provisioned IOPS, storage should be between 100 and 6144. Not used for Amazon Aurora.
    Type: Number
  DBStorageEncrypted:
    Default: false
    AllowedValues:
      - true
      - false
    Description: Whether or not to encrypt the database
    Type: String
  DBStorageType:
    Default: General Purpose (SSD)
    AllowedValues:
      - General Purpose (SSD)
      - Provisioned IOPS
    ConstraintDescription: Must be 'General Purpose (SSD)' or 'Provisioned IOPS'.
    Description: Database storage type. Not used for Amazon Aurora.
    Type: String
  QSS3BucketName:
    Default: 'aws-quickstart'
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen
      (-).
    Description: S3 bucket name for the Quick Start assets. Quick Start bucket name
      can include numbers, lowercase letters, uppercase letters, and hyphens (-).
      It cannot start or end with a hyphen (-).
    Type: String
  QSS3KeyPrefix:
    Default: 'quickstart-atlassian-services/'
    AllowedPattern: ^[0-9a-zA-Z-/]*$
    ConstraintDescription: Quick Start key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), and forward slash (/).
    Description: S3 key prefix for the Quick Start assets. Quick Start key prefix
      can include numbers, lowercase letters, uppercase letters, hyphens (-), and
      forward slash (/).
    Type: String
  SubnetIDs:
    Description: "Subnets to deploy EFS Mounts in. Note: You must specify 2 Availability Zones here; 
      if more are specified, only the first 2 will be used."
    Type: List<AWS::EC2::Subnet::Id>
  VpcId:
    Description: The VPC the security group applies in
    Type: AWS::EC2::VPC::Id

Conditions:
    UseAurora:
      !Equals [%{DatabaseImplementation}, 'Amazon Aurora PostgreSQL']
    UsePostgres:
      !Equals [%{DatabaseImplementation}, 'PostgreSQL']
    GovCloudCondition:
      !Equals [!Ref 'AWS::Region', 'us-gov-west-1']
    UseDatabaseEncryption:
      !Equals [%{DBStorageEncrypted}, true]

Resources:
  AuroraDatabase:
    Type: AWS::CloudFormation::Stack
    Condition: UseAurora
    Properties:
      TemplateURL: 
        !Sub
          - https://${QSS3BucketName}.${QSS3Region}.amazonaws.com/${QSS3KeyPrefix}submodules/quickstart-atlassian-services/submodules/quickstart-amazon-aurora/templates/aurora_postgres.template.yaml
          - QSS3Region: !If ["GovCloudCondition", "s3-us-gov-west-1", "s3"]
      Parameters:
        DBBackupRetentionPeriod: %{DBBackupRetentionPeriod}
        DBInstanceClass: %{DBInstanceClass}
        DBMasterUsername: postgres
        DBEngineVersion: 9.6.11
        DBMasterUserPassword: %{DBMasterUserPassword}
        DBMultiAZ: %{DBMultiAZ}
        DBName: ''
        DBPort: '5432'
        DBAllocatedStorageEncrypted: %{DBStorageEncrypted}
        CustomDBSecurityGroup: %{DBSecurityGroup}
        Subnet1ID: !Select [0, !Split [ ",", %{SubnetIDs}]]
        Subnet2ID: !Select [1, !Split [ ",", %{SubnetIDs}]]
        # NB: The VPCID is not used by the aurora template but it will fail if it is not provided.
        VPCID: %{VpcId}

  PostgresDatabase:
    Type: AWS::CloudFormation::Stack
    Condition: UsePostgres
    Properties:
      TemplateURL:
        !Sub
          - https://${QSS3BucketName}.${QSS3Region}.amazonaws.com/${QSS3KeyPrefix}submodules/quickstart-atlassian-services/templates/quickstart-postgres-for-atlassian-services.yaml
          - QSS3Region: !If ["GovCloudCondition", "s3-us-gov-west-1", "s3"]
      Parameters:
        DBAutoMinorVersionUpgrade: %{DBAutoMinorVersionUpgrade}
        DBBackupRetentionPeriod: %{DBBackupRetentionPeriod}
        DBInstanceClass: %{DBInstanceClass}
        DBIops: %{DBIops}
        DBMasterUsername: postgres
        DBMasterUserPassword: %{DBMasterUserPassword}
        DBMultiAZ: %{DBMultiAZ}
        DBAllocatedStorage: %{DBAllocatedStorage}
        DBAllocatedStorageEncrypted: %{DBStorageEncrypted}
        DBStorageType: %{DBStorageType}
        CustomDBSecurityGroup: %{DBSecurityGroup}
        Subnet1ID: !Select [0, !Split [ ",", %{SubnetIDs}]]
        Subnet2ID: !Select [1, !Split [ ",", %{SubnetIDs}]]

Outputs:
  RDSEndPointAddress:
    Description: The Database Connection String
    Value: !If [UseAurora, !GetAtt AuroraDatabase.Outputs.RDSEndPointAddress, !GetAtt PostgresDatabase.Outputs.RDSEndPointAddress]
  RDSEndPointPort:
    Description: The port the DB endpoint listens on
    Value: !If [UseAurora, !GetAtt AuroraDatabase.Outputs.RDSEndPointPort, !GetAtt PostgresDatabase.Outputs.RDSEndPointPort]
  RDSEncryptionKey:
    Condition: UseDatabaseEncryption
    Description: The alias of the encryption key created for RDS
    Value: !If [UseAurora, !GetAtt AuroraDatabase.Outputs.RDSEncryptionKey, !GetAtt PostgresDatabase.Outputs.RDSEncryptionKey]